
export const auth = {
  AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  AUTH_LOGIN_ERROR: 'AUTH_LOGIN_ERROR',
  AUTH_LOGIN_PENDING: 'AUTH_LOGIN_PENDING',
  AUTH_LOGOUT_SUCCESS: 'AUTH_LOGOUT_SUCCESS',
  AUTH_LOGOUT_ERROR: 'AUTH_LOGOUT_ERROR',
  AUTH_LOGOUT_PENDING: 'AUTH_LOGOUT_PENDING',
  AUTH_AUTHORIZE_SUCCESS: 'AUTH_AUTHORIZE_SUCCESS',
  AUTH_AUTHORIZE_ERROR: 'AUTH_AUTHORIZE_ERROR',
  AUTH_AUTHORIZE_PENDING: 'AUTH_AUTHORIZE_PENDING',
  AUTH_REGISTER_SUCCESS: 'AUTH_REGISTER_SUCCESS',
  AUTH_REGISTER_ERROR: 'AUTH_REGISTER_ERROR',
  AUTH_REGISTER_PENDING: 'AUTH_REGISTER_PENDING',
}

export const home = {
  GET_HOME_SUCCESS: 'GET_HOME_SUCCESS',
  GET_HOME_ERROR: 'GET_HOME_ERROR',
  GET_HOME_PENDING: 'GET_HOME_PENDING',
}

export const book = {
  GET_BOOK_SUCCESS: 'GET_BOOK_SUCCESS',
  GET_BOOK_ERROR: 'GET_BOOK_ERROR',
  GET_BOOK_PENDING: 'GET_BOOK_PENDING',
}

export const reviews = {
  GET_REVIEWS_SUCCESS: 'GET_REVIEWS_SUCCESS',
  GET_REVIEWS_ERROR: 'GET_REVIEWS_ERROR',
  GET_REVIEWS_PENDING: 'GET_REVIEWS_PENDING',
}

export const orders = {
  GET_ORDERS_SUCCESS: 'GET_ORDERS_SUCCESS',
  GET_ORDERS_ERROR: 'GET_ORDERS_ERROR',
  GET_ORDERS_PENDING: 'GET_ORDERS_PENDING',
}

export const order = {
  GET_ORDER_SUCCESS: 'GET_ORDER_SUCCESS',
  GET_ORDER_ERROR: 'GET_ORDER_ERROR',
  GET_ORDER_PENDING: 'GET_ORDER_PENDING',
}

export const orderBooks = {
  GET_ORDER_BOOKS_SUCCESS: 'GET_ORDER_BOOKS_SUCCESS',
  GET_ORDER_BOOKS_ERROR: 'GET_ORDER_BOOKS_ERROR',
  GET_ORDER_BOOKS_PENDING: 'GET_ORDER_BOOKS_PENDING',
}

export const editions = {
  GET_EDITIONS_SUCCESS: 'GET_EDITIONS_SUCCESS',
  GET_EDITIONS_ERROR: 'GET_EDITIONS_ERROR',
  GET_EDITIONS_PENDING: 'GET_EDITIONS_PENDING',
}

export const categories = {
  GET_CATEGORIES_SUCCESS: 'GET_CATEGORIES_SUCCESS',
  GET_CATEGORIES_ERROR: 'GET_CATEGORIES_ERROR',
  GET_CATEGORIES_PENDING: 'GET_CATEGORIES_PENDING',
}

export const searchBooks = {
  GET_SEARCH_BOOKS_SUCCESS: 'GET_SEARCH_BOOKS_SUCCESS',
  GET_SEARCH_BOOKS_ERROR: 'GET_SEARCH_BOOKS_ERROR',
  GET_SEARCH_BOOKS_PENDING: 'GET_SEARCH_BOOKS_PENDING',
}

export const updateAccount = {
  UPDATE_ACCOUNT_SUCCESS: 'UPDATE_ACCOUNT_SUCCESS',
  UPDATE_ACCOUNT_ERROR: 'UPDATE_ACCOUNT_ERROR',
  UPDATE_ACCOUNT_PENDING: 'UPDATE_ACCOUNT_PENDING',
}

export const cart = {
  GET_CART_SUCCESS: 'GET_CART_SUCCESS',
  GET_CART_ERROR: 'GET_CART_ERROR',
  GET_CART_PENDING: 'GET_CART_PENDING',
  ADD_TO_CART_SUCCESS: 'GET_ADD_TO_CART_SUCCESS',
  ADD_TO_CART_ERROR: 'GET_ADD_TO_CART_ERROR',
  ADD_TO_CART_PENDING: 'GET_ADD_TO_CART_PENDING',
  REMOVE_FROM_CART_SUCCESS: 'GET_REMOVE_FROM_CART_SUCCESS',
  REMOVE_FROM_CART_ERROR: 'GET_REMOVE_FROM_CART_ERROR',
  REMOVE_FROM_CART_PENDING: 'GET_REMOVE_FROM_CART_PENDING',
}